FROM node:14
RUN mkdir -p /home/node/frontend/ && chown -R node:node /home/node/frontend/
RUN mkdir -p /home/node/common/ && chown -R node:node /home/node/common/
WORKDIR /home/node
COPY ./frontend/package*.json ./frontend/
COPY ./common/package*.json ./common/
USER node
RUN npm --prefix ./frontend install
RUN npm --prefix ./common install
COPY --chown=node:node ./frontend/ ./frontend/
COPY --chown=node:node ./common/ ./common/
EXPOSE 3000
WORKDIR /home/node/frontend
CMD [ "npm", "start" ]