version: "3.8"

services:
  reverse-proxy:
    image: traefik:v2.3
    command: --providers.docker
    ports:
      - "${PORT:-4200}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    labels:
      - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.backend.middlewares=backend-stripprefix@docker
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.services.backend.loadbalancer.server.port=3000
    build:
      context: .
      dockerfile: Dockerfile-backend
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./backend:/home/node/backend
      - ./common:/home/node/common
      - /home/node/backend/node_modules
      - /home/node/common/node_modules
  frontend:
    labels:
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    build:
      context: .
      dockerfile: Dockerfile-frontend
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/home/node/frontend
      - ./common:/home/node/common
      - /home/node/frontend/node_modules
      - /home/node/common/node_modules
